### ISSUE TITLE
Upload tags report is broken

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3975]
https://danbooru.donmai.us/reports/upload_tags?user_id=52664

```
ActionView::Template::Error exception raised
undefined method `reports_upload_tag_path' for #<#<Class:0x000055a329979498>:0x000055a32aec3a38> Did you mean? reports_upload_tags_path reports_uploads_path reports_upload_tags_url

app/views/posts/partials/index/_preview.html.erb:1:in `block in _app_views_posts_partials_index__preview_html_erb___3294958512830887165_47079632904700'
app/views/posts/partials/index/_preview.html.erb:1:in `_app_views_posts_partials_index__preview_html_erb___3294958512830887165_47079632904700'
app/presenters/post_presenter.rb:78:in `preview'
app/views/reports/upload_tags.html.erb:18:in `block in _app_views_reports_upload_tags_html_erb__4508966179048559077_47079644510440'
app/views/reports/upload_tags.html.erb:16:in `_app_views_reports_upload_tags_html_erb__4508966179048559077_47079644510440'
```

Broken in https://github.com/r888888888/danbooru/commit/bd0bb658b8dd62baa215779e263a21cec6a89c5c#diff-fc4cccc1a6494f9c9fe68a37e39265bcR2.
