### ISSUE TITLE
Exception: undefined method `level_class' for nil:NilClass

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#4015]
https://danbooru.donmai.us/forum_posts/153063:

> https://danbooru.donmai.us/posts/1
>
>The first post on Danbooru is not visible anymore. When trying to access, it gives this:
>
>"undefined method `level_class' for nil:NilClass"

**Comment by evazion** [comment]
Regressed in #4002. Turns out there are around 20k comments that have a null updater_id. These are all old MD Anonymous comments. They should probably have their updater_id reset to `MD Anonymous`.
